KSU: remove duplicates ld.lld: error: duplicate symbol: apply_kernelsu_rules >>> defined at rules.c >>>            drivers/android/kernelsu/selinux/rules.o:(apply_kernelsu_rules) in archive built-in.o >>> defined at rules.c >>>            drivers/kernelsu/selinux/rules.o:(.text+0x0) in archive built-in.o
ld.lld: error: duplicate symbol: ksud_size
>>> defined at embed_ksud.c
>>>            drivers/android/kernelsu/embed_ksud.o:(ksud_size) in archive built-in.o
>>> defined at embed_ksud.c
>>>            drivers/kernelsu/embed_ksud.o:(.bss+0x0) in archive built-in.o

ld.lld: error: duplicate symbol: ksud
>>> defined at embed_ksud.c
>>>            drivers/android/kernelsu/embed_ksud.o:(.rodata+0x0) in archive built-in.o
>>> defined at embed_ksud.c
>>>            drivers/kernelsu/embed_ksud.o:(.rodata+0x0) in archive built-in.o

ld.lld: error: duplicate symbol: ksu_android_ns_fs_check
>>> defined at kernel_compat.c
>>>            drivers/android/kernelsu/kernel_compat.o:(ksu_android_ns_fs_check) in archive built-in.o
>>> defined at kernel_compat.c
>>>            drivers/kernelsu/kernel_compat.o:(.text+0x0) in archive built-in.o

ld.lld: error: duplicate symbol: ksu_filp_open_compat
>>> defined at kernel_compat.c
>>>            drivers/android/kernelsu/kernel_compat.o:(ksu_filp_open_compat) in archive built-in.o
>>> defined at kernel_compat.c
>>>            drivers/kernelsu/kernel_compat.o:(.text+0x108) in archive built-in.o

ld.lld: error: duplicate symbol: ksu_kernel_read_compat
>>> defined at kernel_compat.c
>>>            drivers/android/kernelsu/kernel_compat.o:(ksu_kernel_read_compat) in archive built-in.o
>>> defined at kernel_compat.c
>>>            drivers/kernelsu/kernel_compat.o:(.text+0x290) in archive built-in.o

ld.lld: error: duplicate symbol: ksu_kernel_write_compat
>>> defined at kernel_compat.c
>>>            drivers/android/kernelsu/kernel_compat.o:(ksu_kernel_write_compat) in archive built-in.o
>>> defined at kernel_compat.c
>>>            drivers/kernelsu/kernel_compat.o:(.text+0x2A4) in archive built-in.o

ld.lld: error: duplicate symbol: ksu_strncpy_from_user_nofault
>>> defined at kernel_compat.c
>>>            drivers/android/kernelsu/kernel_compat.o:(ksu_strncpy_from_user_nofault) in archive built-in.o
>>> defined at kernel_compat.c
>>>            drivers/kernelsu/kernel_compat.o:(.text+0x2B8) in archive built-in.o

ld.lld: error: duplicate symbol: ksu_handle_faccessat
>>> defined at sucompat.c
>>>            drivers/android/kernelsu/sucompat.o:(ksu_handle_faccessat) in archive built-in.o
>>> defined at sucompat.c
>>>            drivers/kernelsu/sucompat.o:(.text+0x0) in archive built-in.o

ld.lld: error: duplicate symbol: ksu_handle_stat
>>> defined at sucompat.c
>>>            drivers/android/kernelsu/sucompat.o:(ksu_handle_stat) in archive built-in.o
>>> defined at sucompat.c
>>>            drivers/kernelsu/sucompat.o:(.text+0x164) in archive built-in.o

ld.lld: error: duplicate symbol: ksu_handle_execveat_sucompat
>>> defined at sucompat.c
>>>            drivers/android/kernelsu/sucompat.o:(ksu_handle_execveat_sucompat) in archive built-in.o
>>> defined at sucompat.c
>>>            drivers/kernelsu/sucompat.o:(.text+0x23C) in archive built-in.o

ld.lld: error: duplicate symbol: ksu_sucompat_init
>>> defined at sucompat.c
>>>            drivers/android/kernelsu/sucompat.o:(ksu_sucompat_init) in archive built-in.o
>>> defined at sucompat.c
>>>            drivers/kernelsu/sucompat.o:(.text+0x338) in archive built-in.o

ld.lld: error: duplicate symbol: ksu_sucompat_exit
>>> defined at sucompat.c
>>>            drivers/android/kernelsu/sucompat.o:(ksu_sucompat_exit) in archive built-in.o
>>> defined at sucompat.c
>>>            drivers/kernelsu/sucompat.o:(.text+0x33C) in archive built-in.o

ld.lld: error: duplicate symbol: my_actor
>>> defined at throne_tracker.c
>>>            drivers/android/kernelsu/throne_tracker.o:(my_actor) in archive built-in.o
>>> defined at throne_tracker.c
>>>            drivers/kernelsu/throne_tracker.o:(.text+0x0) in archive built-in.o

ld.lld: error: duplicate symbol: ksu_manager_uid
>>> defined at throne_tracker.c
>>>            drivers/android/kernelsu/throne_tracker.o:(ksu_manager_uid) in archive built-in.o
>>> defined at throne_tracker.c
>>>            drivers/kernelsu/throne_tracker.o:(.data+0x0) in archive built-in.o

ld.lld: error: duplicate symbol: search_manager
>>> defined at throne_tracker.c
>>>            drivers/android/kernelsu/throne_tracker.o:(search_manager) in archive built-in.o
>>> defined at throne_tracker.c
>>>            drivers/kernelsu/throne_tracker.o:(.text+0x3A8) in archive built-in.o

ld.lld: error: duplicate symbol: handle_sepolicy
>>> defined at rules.c
>>>            drivers/android/kernelsu/selinux/rules.o:(handle_sepolicy) in archive built-in.o
>>> defined at rules.c
>>>            drivers/kernelsu/selinux/rules.o:(.text+0x674) in archive built-in.o

ld.lld: error: duplicate symbol: track_throne
>>> defined at throne_tracker.c
>>>            drivers/android/kernelsu/throne_tracker.o:(track_throne) in archive built-in.o
>>> defined at throne_tracker.c
>>>            drivers/kernelsu/throne_tracker.o:(.text+0x450) in archive built-in.o

ld.lld: error: duplicate symbol: ksu_throne_tracker_init
>>> defined at throne_tracker.c
>>>            drivers/android/kernelsu/throne_tracker.o:(ksu_throne_tracker_init) in archive built-in.o
>>> defined at throne_tracker.c
>>>            drivers/kernelsu/throne_tracker.o:(.text+0x46C) in archive built-in.o

ld.lld: error: duplicate symbol: ksu_throne_tracker_exit
>>> defined at throne_tracker.c
>>>            drivers/android/kernelsu/throne_tracker.o:(ksu_throne_tracker_exit) in archive built-in.o
>>> defined at throne_tracker.c
>>>            drivers/kernelsu/throne_tracker.o:(.text+0x79C) in archive built-in.o

ld.lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
make[1]: *** [/home/runner/work/kernel_samsung_M215F_CVH1/kernel_samsung_M215F_CVH1/Makefile:1270: vmlinux] Error 1
make[1]: Leaving directory '/home/runner/work/kernel_samsung_M215F_CVH1/kernel_samsung_M215F_CVH1/out'
make: *** [Makefile:146: sub-make] Error 2
This partially reverts commit 4166832e4fc0151a590257bffccc831b26c622f8.